name: CI/CD Product Manager API

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    name: CI product manager api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test app
        run: mvn clean install

#  cd:
#    name: CD product manager api
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push develop Docker image
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: fredsonchaves07/product-manager-api:latest